linters:
  enable:
    - deadcode
    - errcheck
    - goconst
    - golint
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - structcheck
    - unconvert
    - varcheck
    - govet
    - goimports
    - prealloc
    - unused
    - staticcheck
    - gosimple
  disable:
    - megacheck
linters-settings:
  lll:
    line-length: 160
  goconst:
    min-occurrences: 4
  govet:
    check-shadowing: true
