version: 2
workflows:
  version: 2
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    env:
      GO111MODULE: on
    working_directory: ~/log
    steps:
      - checkout
      - run: make
      - run: make test
      - run: make lint
